name = "vibebase"
main = "packages/core/src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers Assets for dashboard
assets = { directory = "packages/dashboard/dist", binding = "ASSETS", run_worker_first = true }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding (新規作成用 - IDなし)
[[d1_databases]]
binding = "DB"
database_name = "vibebase-db"

# R2 Storage bindings (新規作成用 - IDなし)
[[r2_buckets]]
binding = "SYSTEM_STORAGE"
bucket_name = "vibebase-system"

[[r2_buckets]]
binding = "USER_STORAGE"
bucket_name = "vibebase-storage"

# KV Namespace for sessions (新規作成用 - IDなし)
[[kv_namespaces]]
binding = "SESSIONS"

# Durable Objects for realtime functionality
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeConnectionManager"

[[migrations]]
tag = "v1"
new_classes = [ "RealtimeConnectionManager" ]

# Cron Triggers for realtime event processing
[triggers]
crons = ["*/5 * * * *"]  # 5分ごとに実行

# Environment variables
[vars]
ENVIRONMENT = "production"
VIBEBASE_DEPLOY_MODE = "deploy-button"
VIBEBASE_AUTH_URL = "https://auth.vibebase.workers.dev"