name = "__WORKER_NAME__"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "__ACCOUNT_ID__"

# Workers Assets for dashboard
assets = { directory = "../dashboard/dist", binding = "ASSETS" }

# Enable Workers Logs
[observability]
enabled = true

# D1 Database binding (will be auto-configured during setup)
[[d1_databases]]
binding = "DB"
database_name = "vibebase-db"
database_id = "__DATABASE_ID__"

# R2 Storage bindings
[[r2_buckets]]
binding = "SYSTEM_STORAGE"
bucket_name = "vibebase-system"

[[r2_buckets]]
binding = "USER_STORAGE"
bucket_name = "vibebase-storage"

# KV Namespace for sessions (will be auto-configured during setup)
[[kv_namespaces]]
binding = "SESSIONS"
id = "__KV_NAMESPACE_ID__"

[vars]
ENVIRONMENT = "production"
VIBEBASE_AUTH_URL = "https://auth.vibebase.workers.dev"
DEPLOYMENT_DOMAIN = "__DEPLOYMENT_DOMAIN__"
WORKER_NAME = "__WORKER_NAME__"
DOMAIN = "__DEPLOYMENT_DOMAIN__"
VAPID_PUBLIC_KEY = "__VAPID_PUBLIC_KEY__"
VAPID_SUBJECT = "__VAPID_SUBJECT__"

[env.development.vars]
ENVIRONMENT = "development"
VIBEBASE_AUTH_URL = "https://auth.vibebase.workers.dev"
DEPLOYMENT_DOMAIN = "localhost:8787"
WORKER_NAME = "__WORKER_NAME__-dev"
DOMAIN = "localhost:8787"

# Durable Objects for realtime functionality
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeConnectionManager"

[[migrations]]
tag = "v1"
new_classes = [ "RealtimeConnectionManager" ]

# Cron Triggers for realtime event processing
[triggers]
crons = ["*/5 * * * *"]  # 5分ごとに実行