name: Debug Comment
on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Debug Info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Author: ${{ github.event.comment.user.login }}"
          echo "Association: ${{ github.event.comment.author_association }}"
          echo "Is PR: ${{ github.event.issue.pull_request != null }}"
          echo "Comment: ${{ github.event.comment.body }}"